### ISSUE TITLE
Create a User Model

### ISSUE THREAD

**Issue by SomTambe** [SPO-Career-Portal/SCP-Backend#1]
You need to create a user model. Set up a model named `user` which stores the following fields -
- name
- username (IITK)
- roll number
- batch (eg. Y18, Y19, etc)
- program (eg. BT, BT-BS, BS, BS-BS, MT, Ph.D., etc)
- department
- GitHub profile link
- Linkedin profile link
- Master CV drive link
- Resume 1 drive link
- Resume 2 drive link

**Comment by navneet-28** [comment]
I can work on this!
