### ISSUE TITLE
Fetch User data API

### ISSUE THREAD

**Issue by SomTambe** [SPO-Career-Portal/SCP-Backend#11]
Create an API which fetches the users data from the database.
It should work in the following fashion - 
```
method: GET
Successful : 200_OK
Unsuccessful : 404_BAD_REQUEST / 401_UNAUTHORIZED

Response : {
            "roll",
            "username",
            "name",
            "email",
            ...
}
```
The response should contain the required fields.
You can refer to [this](https://github.com/pclubiitk/Campus-Discuss-Backend) to check how it had been implemented in campus discuss.

**Comment by navneet-28** [comment]
I'll work on this.

**Comment by uditpd3000** [comment]
I would also like to work on this with @navneet-28, May I?

**Comment by shashank1310** [comment]
i would like to work  on it

**Comment by SomTambe** [comment]
Sure @navneet-28 and @uditpd3000 can work together.
