### ISSUE TITLE
Add Login and Logout systems

### ISSUE THREAD

**Issue by SomTambe** [SPO-Career-Portal/SCP-Backend#12]
Refer to [this](https://www.django-rest-framework.org/api-guide/authentication/) and [this PR](https://github.com/pclubiitk/Campus-Discuss-Backend/pull/39) to get an idea of what you must do.

You must implement Login and logout systems for the `User` model.

You may work on a team on this PR.

**Comment by sanchit-sinha** [comment]
I and @shashank1310 are working on this issue.
