### ISSUE TITLE
Fetch Intern Data for a given user.

### ISSUE THREAD

**Issue by SomTambe** [SPO-Career-Portal/SCP-Backend#13]
You need to make an API which fetches the internships a user is eligible for. You may use session credentials for this, send a `GET` or a `POST` api (`GET` should do the work) and then get a list of all the internships he/she is eligible for by checking the dept, program, etc.

**Comment by sanchit-sinha** [comment]
I'll be glad to work on this.

**Comment by shashank1310** [comment]
If possible i would like to work on it with @sanchit-sinha

**Comment by SomTambe** [comment]
@sanchit-sinha @shashank1310 Discuss it with yourselves whether you want to work together and let me know accordingly.
