### ISSUE TITLE
Create Intern model

### ISSUE THREAD

**Issue by SomTambe** [SPO-Career-Portal/SCP-Backend#2]
You have to create the model for Internships here. This model is supposed to store the data for all the internships that are updated by SPO. The fields here are really straightforward - 

- Intern Name
- Company
- Duration
- Role
- Description
- Eligible batches
- Eligible branches
- Eligible Programmes
- Deadline
- Intern Start Month
- Intern End Month

**Comment by parinayc20** [comment]
May I work on this.
