### ISSUE TITLE
Create a Registration model

### ISSUE THREAD

**Issue by SomTambe** [SPO-Career-Portal/SCP-Backend#20]
Create a new model for registrations. Basically this will cater to the registrations for placements and interns.
This should contain the following fields -
- User (an object from the User model)
- Internship registered for (an object from the Internship model)
- Placement registered for (an object from the placement model)

So it is obvious that a person cannot register for an internship or a placement at the same time. So understand it like this -
A person registers for X intern, so the entry of in this registrations database will consist of the User object for that user, the Internship object which the user has registered for, and a False value in the placement object (I don't know if this is possible or not). For a placement, the internship field will go False (now how these entries will be added is for an API which you'll create in the future).

I want to know if this is possible. I am ready to hear you guys inputs for this and how you would go about implementing this. You can give alternative suggestions too for going about this thing.

**Comment by namangup** [comment]
Instead of False we can have a `None` value. Makes more sense to me. Also, we should have one more check whether the user is eligible for internship or placement drive as a whole. Both intern and placement are disjoint, a particular batch is only eligible for one of them.

**Comment by shashank1310** [comment]
I will work on this issue.

**Comment by parinayc20** [comment]
@SomTambe @namangup  @shashank1310  ig all this can be made much easier if in the user model, we add two more hidden fields, placements_applied_for and interns_applied_for. These will be non-editable from the admin side and will be Json fields with default=list

**Comment by SomTambe** [comment]
>we add two more hidden fields, placements_applied_for and interns_applied_for. These will be non-editable from the admin side and will be Json fields with default=list

This also seems good to me. We can add the respective APIs accordingly to modify these values. Also keep them editable from the admin side (I don't know how will you make it non-editable in the first place) but we aren't going to provide an interface for the admin to edit these fields, these can be done only from the command line as we do it for our debugging purposes.
