### ISSUE TITLE
Create a unique identifier field in both placement and internship models

### ISSUE THREAD

**Issue by SomTambe** [SPO-Career-Portal/SCP-Backend#21]
So this was required because of two things -
- If I wanted to refer to a placement or an internship from an API, the best way would be to insert a unique identifier for this.
- One would argue, we have the `primary_key` set to `id`, but still something like `8743b52063cd` seems a lot cooler than `43` or `44`.

So you need to do this -
1. Create a 8-bit hash using any possible algorithm of the `name + timestamp` which gets initialized to this value right when the object is created itself in the database.
2. Do 1.

This should be fairly easy to implement and I want whoever is doing this to do it for both Placements as well as Internships model.

**Comment by parinayc20** [comment]
I guess there might be a problem of collisions in a 8 character hash. So I think we should increase the size of that hash a bit. What do you think?
Or we might make it a keyed hashing with timestamp as the key and name as the string.

**Comment by SomTambe** [comment]
@parinayc20 Why do you think a 8 character hash would cause a collision? The possibility is higher than that of a 16 character hash but it's still very low. 
Nvm I have no problem with a 16 character hash apart from the fact it would occupy a larger memory.
You can go ahead with any type you feel is right.
Also I think keyed hashing is an overkill, but you can do anything that is computationally inexpensive compared to the other.

**Comment by namangup** [comment]
@SomTambe is there any other advantage except the hash looking cooler? Anyway, we'll be having checks in place if a person is eligible for the interns etc which prevents unauthorized access If the motivation is to prevent automation by a script, how would a hash prevent that? 

And we could just have a field intern/placement code something like (GOOGSWE in case of Google Software Dev Engineer). This code can be added at the time of populating the db with details of intern/placement. It also looks more logical.

@parinayc20 what do you think?

**Comment by SomTambe** [comment]
@namangup Yes this placement code thing also seems logical, but it would collide in the case of 2 same interns year after year right? That is why hashing would seem logical.
The only thing why I thought it would be more useful was to have the register API in this format -
```
request:{
              User:"username",
              Internship:"internship hash",
              Placement:False
}
```
This could also be done with the help of the normal id.

**Comment by namangup** [comment]
> but it would collide in the case of 2 same interns year after year right?

Yes in that case the hash should be based on created_at field also. What are the downsides of having id is the identifier apart from it being not cool?

**Comment by SomTambe** [comment]
@namangup But I already mentioned that we will append the timestamp of the creation of that entry at the end and then hash it. So what's the argument?

**Comment by parinayc20** [comment]
@namangup I agree with @SomTambe because after adding the code and basing it with the timestamp of creation would be similar to thing we are doing currently.
