### ISSUE TITLE
User Registration, Activation, Password Change

### ISSUE THREAD

**Issue by namangup** [SPO-Career-Portal/SCP-Backend#25]
Follow Campus-Discuss-Backend users model, add the following APIs
path('register/verify/code=<str:token>/',SetPasswordAndActivate,name="email-activator"),
path('register/',RegistrationView.as_view(),name="registration"),
path('resetpassemail/',ResetPasswordEmail,name="resetpass-email"),
path('resetpass/code=<str:token>/',ResetPassword,name="resetpass"),

Make changes in the code wherever required.

**Comment by uditpd3000** [comment]
I want to work on this issue.
