### ISSUE TITLE
Create Placement model

### ISSUE THREAD

**Issue by SomTambe** [SPO-Career-Portal/SCP-Backend#3]
You have to create the model for Placements here. This model is supposed to store the data for all the placements that are updated by SPO. The fields here are really straightforward -

- Placement Name
- Company
- Role
- Description
- Eligible batches
- Eligible branches
- Eligible Programmes
- Deadline

**Comment by Shubham63-hub** [comment]
i can work on this.

**Comment by parinayc20** [comment]
May I work on this
